---
apiVersion: v2
name: flat-runs-field-updater
description: Chart for deploying the flat runs field updater
type: application
version: 0.1.0
appVersion: "0.33.0"
home: https://wandb.ai
icon: https://wandb.ai/logo.svg
maintainers:
  - name: wandb
    email: support@wandb.com
    url: https://wandb.com
