apiVersion: v2
name: wandb
description: A Helm chart for deploying W&B to Kubernetes
type: application
version: 0.3.2
appVersion: "0.47.2"
icon: https://wandb.ai/logo.svg
maintainers:
  - name: wandb
    email: support@wandb.com
    url: https://wandb.com
