apiVersion: v2
name: wandb
description: A Helm chart for deploying W&B to Kubernetes
type: application
version: 0.2.4
appVersion: "0.42.0"
icon: https://wandb.ai/logo.svg
maintainers:
  - name: wandb
    email: support@wandb.com
    url: https://wandb.com
