apiVersion: v2
name: launch-agent
icon: https://em-content.zobj.net/thumbs/240/apple/354/rocket_1f680.png
description: A Helm chart for running the W&B Launch Agent in Kubernetes
type: application
version: 0.7.0
maintainers:
  - name: wandb
    email: support@wandb.com
    url: https://wandb.com
