apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-filemeta-configmap
  labels:
    {{- include "wandb.labels" . | nindent 4 }}
data:
  GORILLA_IMAGE_TAG: "{{ .Values.filemeta.image.tag }}"
