apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-internal-signer-configmap
  labels:
    {{- include "wandb.labels" . | nindent 4 }}
data:
  INTERNAL_SIGNER_K8S_SECRET_NAME: "{{ .Release.Name }}-internal-signer"
  INTERNAL_SIGNER_K8S_NAMESPACE: "{{ .Release.Namespace }}"
