apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-parquet-metadata-cache-configmap
  labels:
    {{- include "wandb.commonLabels" . | nindent 4 }}
data:
  # Port configuration
  GORILLA_PARQUET_METADATA_CACHE_PORT: "9091"
  
  GORILLA_MAX_COLUMN_CHUNKS: "10000"

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-parquet-metadata-cache-secret
  labels:
    {{- include "wandb.commonLabels" . | nindent 4 }}
data: {}
