# Any time the password is not a map, we need to create this secret manually
{{- if not (kindIs "map" .Values.global.email.smtp.password) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-smtp-secret
  labels:
    {{- include "wandb.commonLabels" . | nindent 4 }}
data:
    SMTP_PASSWORD: {{ include "wandb.smtp.password" . | b64enc }}
{{- end }}
