apiVersion: v2
name: agent
type: application
description: A Helm chart for Kubernetes

version: 0.1.1
appVersion: "0.33.0"

home: https://wandb.ai
icon: https://wandb.ai/logo.svg

maintainers:
  - name: wandb
    email: support@wandb.com
    url: https://wandb.com
