apiVersion: v2
name: operator
description: A Helm chart for Weights & Biases operator
type: application
version: 1.0.2
appVersion: "1.0.0"
maintainers:
  - name: wandb
    email: support@wandb.com
    url: https://wandb.com
