apiVersion: apps.wandb.com/v1
kind: WeightsAndBiases
metadata:
  labels:
    app.kubernetes.io/name: weightsandbiases
    app.kubernetes.io/instance: wandb
    wandb.ai/console-default: "true"
  name: wandb
spec:
  values:
    version: https://github.com/wandb/cdk8s
