apiVersion: v2
name: wandb-base
description: A generic helm chart for deploying services to kubernetes
type: application
version: 0.2.0
icon: https://wandb.ai/logo.svg

maintainers:
  - name: wandb
    email: support@wandb.com
    url: https://wandb.com
