apiVersion: apps.wandb.com/v1
kind: WeightsAndBiases
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: weightsandbiases
    app.kubernetes.io/instance: wandb
spec: {{ toYaml .Values.spec | nindent 2 }}